@echo off
REM ============================================================
REM  [AI RULES] DO NOT EDIT THIS FILE WITH CHINESE CHARACTERS
REM  - Only use English/ASCII characters for echo and comments
REM  - This file MUST be saved in GBK/ANSI encoding
REM  - UTF-8 encoding will cause this script to crash
REM ============================================================
chcp 65001 >nul
setlocal enabledelayedexpansion

title Amazon Toolbox - One Click Publish
echo ============================================
echo   Amazon Toolbox - One Click Publish
echo ============================================
echo.

cd /d "%~dp0"

if not exist "package.json" (
    echo [ERROR] package.json not found!
    echo.
    pause
    exit /b 1
)

echo [INFO] Reading current version...
for /f "tokens=2 delims=:, " %%a in ('findstr /c:"\"version\"" package.json') do set CURRENT_VERSION=%%~a
echo Current version: !CURRENT_VERSION!
echo.

set /p NEW_VERSION="Enter new version (press Enter to use !CURRENT_VERSION!): "
if "!NEW_VERSION!"=="" set NEW_VERSION=!CURRENT_VERSION!

echo.
echo [INFO] Target version: !NEW_VERSION!
echo.

echo [1/4] Building (version not changed yet)...
echo.
call build.bat
echo.

REM Check if build succeeded by looking for exe file in release directory
set BUILD_OK=0
dir /b "release\*.exe" 2>nul | findstr /v /i "elevate.exe" >nul 2>&1
if not errorlevel 1 set BUILD_OK=1

if "!BUILD_OK!"=="0" (
    echo [ERROR] Build failed! No installer found in release directory.
    echo [INFO] package.json version NOT changed, you can retry with same version.
    echo.
    pause
    exit /b 1
)
echo Build complete!
echo.

echo [2/4] Updating version to !NEW_VERSION!...
python _update_version.py !NEW_VERSION!
if errorlevel 1 (
    echo [ERROR] Version update failed!
    pause
    exit /b 1
)
echo Version updated to !NEW_VERSION!.
echo.

echo [3/4] Uploading files to server...
echo.

set RELEASE_DIR=release
set SERVER_URL=http://8.130.113.104:8000

if not exist "!RELEASE_DIR!" (
    echo [ERROR] Release directory not found!
    echo.
    pause
    exit /b 1
)

set SCRIPT_DIR=%~dp0

REM Get admin token for upload authentication
echo [AUTH] Logging in to get admin token...
set ADMIN_PASSWORD=
set /p ADMIN_PASSWORD="Enter admin password (default: admin123): "
if "!ADMIN_PASSWORD!"=="" set ADMIN_PASSWORD=admin123

for /f "delims=" %%t in ('powershell -NoProfile -ExecutionPolicy Bypass -Command "$r = Invoke-RestMethod -Uri '!SERVER_URL!/api/auth/admin-login' -Method POST -ContentType 'application/json' -Body ('{\"password\":\"' + '!ADMIN_PASSWORD!' + '\"}'); if ($r.success) { Write-Host $r.data.token } else { Write-Host 'AUTH_FAILED' }"') do set ADMIN_TOKEN=%%t

if "!ADMIN_TOKEN!"=="" (
    echo [ERROR] Failed to get admin token!
    echo.
    pause
    exit /b 1
)
if "!ADMIN_TOKEN!"=="AUTH_FAILED" (
    echo [ERROR] Admin login failed! Wrong password?
    echo.
    pause
    exit /b 1
)
echo [OK] Admin token obtained.
echo.

if exist "!RELEASE_DIR!\latest.yml" (
    echo Uploading latest.yml...
    powershell -NoProfile -ExecutionPolicy Bypass -File "!SCRIPT_DIR!upload_file.ps1" -FilePath "!RELEASE_DIR!\latest.yml" -ServerUrl "!SERVER_URL!" -Token "!ADMIN_TOKEN!"
    if errorlevel 1 (
        echo [ERROR] latest.yml upload failed!
        echo.
        pause
        exit /b 1
    )
) else (
    echo [WARN] latest.yml not found, skipping.
)

set EXE_FOUND=0
for %%f in ("!RELEASE_DIR!\*.exe") do (
    if not "%%~nxf"=="elevate.exe" (
        set EXE_FOUND=1
        echo Uploading %%~nxf...
        powershell -NoProfile -ExecutionPolicy Bypass -File "!SCRIPT_DIR!upload_file.ps1" -FilePath "%%f" -ServerUrl "!SERVER_URL!" -Token "!ADMIN_TOKEN!"
        if errorlevel 1 (
            echo [ERROR] %%~nxf upload failed!
            echo.
            pause
            exit /b 1
        )
    )
)

if "!EXE_FOUND!"=="0" (
    echo [WARN] No exe installer files found.
)

for %%f in ("!RELEASE_DIR!\*.blockmap") do (
    echo Uploading %%~nxf...
    powershell -NoProfile -ExecutionPolicy Bypass -File "!SCRIPT_DIR!upload_file.ps1" -FilePath "%%f" -ServerUrl "!SERVER_URL!" -Token "!ADMIN_TOKEN!"
)

echo.
echo [4/4] Done!
echo.
echo ============================================
echo   Publish Success! Version: !NEW_VERSION!
echo   Server: !SERVER_URL!
echo ============================================
echo.
endlocal
pause