@echo off
REM ============================================================
REM  [AI RULES] DO NOT EDIT THIS FILE WITH CHINESE CHARACTERS
REM  - Only use English/ASCII characters for echo and comments
REM  - This file MUST be saved in GBK/ANSI encoding
REM  - UTF-8 encoding will cause this script to crash
REM ============================================================
chcp 65001 >nul

echo ============================================
echo   Amazon Toolbox - One Click Start
echo ============================================
echo.

cd /d "%~dp0"

:: ===== Check Python =====
echo [CHECK] Checking Python environment...
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python not found, please install Python 3.8+
    echo Download: https://www.python.org/downloads/
    pause
    exit /b 1
)
echo [OK] Python installed

:: ===== Check backend dependencies =====
echo.
echo [CHECK] Checking backend dependencies...
if not exist "backend\" (
    echo [ERROR] Backend directory not found!
    pause
    exit /b 1
)
cd backend
echo [INFO] Checking fastapi module...
pip show fastapi >nul 2>&1
if errorlevel 1 (
    echo [INSTALL] Installing backend dependencies first run...
    echo [INFO] This may take a few minutes...
    pip install -r requirements.txt
    if errorlevel 1 (
        echo [ERROR] Dependency installation failed!
        cd ..
        pause
        exit /b 1
    )
    echo [OK] Backend dependencies installed
) else (
    echo [OK] Backend dependencies ready
)
cd ..

:: ===== Check Node.js =====
echo.
echo [CHECK] Checking Node.js environment...
node --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js not found, please install Node.js 16+
    echo Download: https://nodejs.org/
    pause
    exit /b 1
)
echo [OK] Node.js installed

:: ===== Check frontend dependencies =====
echo.
echo [CHECK] Checking frontend dependencies...
if not exist "node_modules\" (
    echo [INSTALL] Installing frontend dependencies first run...
    echo [INFO] This may take a few minutes...
    call npm install
    if errorlevel 1 (
        echo [ERROR] Frontend dependency installation failed!
        pause
        exit /b 1
    )
    echo [OK] Frontend dependencies installed
) else (
    echo [OK] Frontend dependencies ready
)

:: ===== Start backend =====
echo.
echo [START] Starting backend service...
start "Backend" cmd /k "cd /d %~dp0backend && set DEBUG=true && python main.py"

:: ===== Wait for backend =====
echo [WAIT] Waiting for backend service to start...
set retry=0
:wait_backend
timeout /t 2 /nobreak >nul
set /a retry+=1
echo [INFO] Checking backend status... attempt %retry%/15
curl -s http://localhost:8000/api/health >nul 2>&1
if errorlevel 1 (
    if %retry% LSS 15 (
        goto wait_backend
    ) else (
        echo [WARN] Backend startup timeout, please check backend window
    )
) else (
    echo [OK] Backend service ready
)

:: ===== Start frontend =====
echo.
echo [START] Starting frontend service...
start "Frontend" cmd /k "cd /d %~dp0 && npm run dev"

echo.
echo ============================================
echo   Startup complete!
echo ============================================
echo.
echo  Frontend:  http://localhost:3000
echo  Backend:   http://localhost:8000
echo  API Docs:  http://localhost:8000/docs
echo  Admin:     http://localhost:3000/#/admin/login
echo.
echo  Default admin password: admin123
echo.
echo  Press any key to close this window (services keep running)
pause >nul