@echo off
REM ============================================================
REM  [AI RULES] DO NOT EDIT THIS FILE WITH CHINESE CHARACTERS
REM  - Only use English/ASCII characters for echo and comments
REM  - This file MUST be saved in GBK/ANSI encoding
REM  - UTF-8 encoding will cause this script to crash
REM ============================================================
chcp 65001 >nul
setlocal enabledelayedexpansion

title Amazon Toolbox - One Click Publish
echo ============================================
echo   Amazon Toolbox - One Click Publish
echo ============================================
echo.

cd /d "%~dp0"

if not exist "package.json" (
    echo [ERROR] package.json not found!
    echo.
    pause
    exit /b 1
)

echo [INFO] Reading current version...
for /f "tokens=2 delims=:, " %%a in ('findstr /c:"\"version\"" package.json') do set CURRENT_VERSION=%%~a
echo Current version: !CURRENT_VERSION!
echo.

set /p NEW_VERSION="Enter new version (press Enter to use !CURRENT_VERSION!): "
if "!NEW_VERSION!"=="" set NEW_VERSION=!CURRENT_VERSION!

echo.
echo [INFO] Target version: !NEW_VERSION!
echo.

echo [1/4] Updating version to !NEW_VERSION!...
python _update_version.py !NEW_VERSION!
if errorlevel 1 (
    echo [ERROR] Version update failed!
    pause
    exit /b 1
)
echo Version updated to !NEW_VERSION!.
echo.

echo [2/4] Building with new version...
echo.
call build.bat
echo.

REM Check if build succeeded by looking for exe file in release directory
set BUILD_OK=0
dir /b "release\*.exe" 2>nul | findstr /v /i "elevate.exe" >nul 2>&1
if not errorlevel 1 set BUILD_OK=1

if "!BUILD_OK!"=="0" (
    echo [ERROR] Build failed! No installer found in release directory.
    echo [INFO] package.json version was changed to !NEW_VERSION!, but build failed.
    echo.
    pause
    exit /b 1
)
echo Build complete!
echo.

echo [3/4] Uploading files to server (fast mode)...
echo.

set RELEASE_DIR=release

if not exist "!RELEASE_DIR!" (
    echo [ERROR] Release directory not found!
    echo.
    pause
    exit /b 1
)

REM Collect all files to upload
set UPLOAD_FILES=
if exist "!RELEASE_DIR!\latest.yml" set UPLOAD_FILES=!UPLOAD_FILES! "!RELEASE_DIR!\latest.yml"

for %%f in ("!RELEASE_DIR!\*.exe") do (
    if not "%%~nxf"=="elevate.exe" set UPLOAD_FILES=!UPLOAD_FILES! "%%f"
)

for %%f in ("!RELEASE_DIR!\*.blockmap") do (
    set UPLOAD_FILES=!UPLOAD_FILES! "%%f"
)

if "!UPLOAD_FILES!"=="" (
    echo [WARN] No files to upload.
) else (
    echo Uploading: !UPLOAD_FILES!
    python fast_upload.py !UPLOAD_FILES!
    if errorlevel 1 (
        echo [ERROR] Upload failed!
        echo.
        pause
        exit /b 1
    )
)

echo.
echo [4/4] Done!
echo.
echo ============================================
echo   Publish Success! Version: !NEW_VERSION!
echo   Server: !SERVER_URL!
echo ============================================
echo.
endlocal
pause