@echo off
REM ============================================================
REM  [AI RULES] DO NOT EDIT THIS FILE WITH CHINESE CHARACTERS
REM  - Only use English/ASCII characters for echo and comments
REM  - This file MUST be saved in GBK/ANSI encoding
REM  - UTF-8 encoding will cause this script to crash
REM ============================================================
setlocal enabledelayedexpansion
echo ========================================
echo   Save Code to Git
echo ========================================
echo.

git add .

if not "%~1"=="" (
    set "COMMIT_MSG=%~1"
) else (
    for /f "tokens=1-2 delims= " %%a in ('echo %date% %time%') do set "COMMIT_MSG=update: %%a %%b"
)

if "!COMMIT_MSG!"=="" set "COMMIT_MSG=update"

git commit -m "!COMMIT_MSG!"

if %errorlevel% neq 0 (
    echo.
    echo [INFO] No changes to commit, or commit failed
    pause
    exit /b
)

echo.
echo [OK] Code saved!
echo.

git push origin main

if %errorlevel% neq 0 (
    echo.
    echo [INFO] Push to GitHub failed, please check network connection
    pause
    exit /b
)

echo [OK] Code pushed to GitHub!
pause