/* eslint-disable */
/** Generated by scripts/generate_openapi_types.py. Do not edit manually. */
export interface components {
  schemas: {
    "APIResponse_BusinessBatchItemResponse_": { "data"?: components['schemas']["BusinessBatchItemResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_BusinessBatchResponse_": { "data"?: components['schemas']["BusinessBatchResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_BusinessBootstrapResponse_": { "data"?: components['schemas']["BusinessBootstrapResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_ExpenseAttachmentResponse_": { "data"?: components['schemas']["ExpenseAttachmentResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_ExpenseCategoryResponse_": { "data"?: components['schemas']["ExpenseCategoryResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_ExpenseRecordResponse_": { "data"?: components['schemas']["ExpenseRecordResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_ExpenseRenewalConfirmResponse_": { "data"?: components['schemas']["ExpenseRenewalConfirmResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_ExpenseRenewalResponse_": { "data"?: components['schemas']["ExpenseRenewalResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_ExpenseSummaryResponse_": { "data"?: components['schemas']["ExpenseSummaryResponse"] | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_NoneType_": { "data"?: null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_list_BusinessBatchResponse__": { "data"?: Array<components['schemas']["BusinessBatchResponse"]> | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_list_ExpenseCategoryResponse__": { "data"?: Array<components['schemas']["ExpenseCategoryResponse"]> | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "APIResponse_list_dict_str__Any___": { "data"?: Array<{  }> | null; "message"?: string; "page"?: number | null; "page_size"?: number | null; "success"?: boolean; "total"?: number | null; "total_pages"?: number | null }
    "AdminLoginRequest": { "password": string; "username"?: string }
    "AnnouncementCreate": { "app_version"?: string | null; "audience"?: "all" | "consumer" | "business"; "category"?: "system" | "update" | "activity" | "maintenance" | null; "content": string; "expires_at"?: string | null; "presentation"?: "banner" | "modal" | null; "priority"?: number; "severity"?: "info" | "important" | "critical"; "starts_at"?: string | null; "status"?: "draft" | "published" | "expired"; "title": string; "type"?: string | null }
    "AnnouncementUpdate": { "app_version"?: string | null; "audience"?: "all" | "consumer" | "business" | null; "category"?: "system" | "update" | "activity" | "maintenance" | null; "content"?: string | null; "expires_at"?: string | null; "presentation"?: "banner" | "modal" | null; "priority"?: number | null; "severity"?: "info" | "important" | "critical" | null; "starts_at"?: string | null; "status"?: "draft" | "published" | "expired" | null; "title"?: string | null; "type"?: string | null }
    "AuthCodeGenerate": { "count"?: number; "duration_days"?: number | null; "max_devices"?: number | null; "plan_id"?: number | null; "platform_scope"?: string | null; "scene_type"?: string | null; "seat_limit"?: number | null }
    "AuthCodeResponse": { "code": string; "created_at"?: string | null; "device_id"?: string | null; "device_name"?: string | null; "device_used"?: number | null; "devices"?: Array<components['schemas']["DeviceResponse"]>; "entitlements"?: {  }; "expires_at"?: string | null; "id": number; "max_devices"?: number | null; "plan_id"?: number | null; "plan_name"?: string | null; "platform_scope"?: Array<string> | null; "product_type"?: string; "scene_type"?: string | null; "seat_limit"?: number | null; "seat_used"?: number | null; "status": string; "user_id"?: number | null }
    "AuthCodeUpdate": { "device_id"?: string | null; "device_name"?: string | null; "expires_at"?: string | null; "max_devices"?: number | null; "status"?: string | null }
    "BatchCreate": { "client_batch_id": string; "tool_id": string; "tool_name": string; "total_count": number }
    "BatchFinish": { "status": "completed" | "cancelled" | "interrupted" }
    "BatchImportItem": { "category": string; "content": string; "keywords"?: Array<string> | null; "priority"?: string | null; "title": string }
    "BatchItemUpdate": { "account_label_masked": string; "customer_message"?: string | null; "intervention_type"?: "login" | "captcha" | "two_factor" | "page_confirmation" | "other" | null; "status": "pending" | "running" | "waiting_user" | "completed" | "failed" | "cancelled" }
    "BatchUpdate": { "completed_count"?: number; "failed_count"?: number; "pending_count"?: number; "running_count"?: number; "status"?: "running" | "completed" | "cancelled" | "interrupted" | null; "waiting_count"?: number }
    "Body_add_expense_attachment_api_expenses__expense_id__attachments_post": { "file": string }
    "Body_stage_release_api_updates_releases_stage_post": { "files": Array<string>; "version"?: string | null }
    "Body_update_platforms_api_tools_platforms_put": { "platforms": Array<unknown> }
    "Body_update_tool_categories_api_tools_categories_put": { "categories": Array<unknown> }
    "BusinessBatchItemResponse": { "account_label_masked"?: string | null; "client_item_id": string; "completed_at"?: string | null; "customer_message"?: string | null; "intervention_type"?: string | null; "started_at"?: string | null; "status": string; "updated_at"?: string | null; [key: string]: unknown }
    "BusinessBatchResponse": { "client_batch_id": string; "completed_count": number; "failed_count": number; "finished_at"?: string | null; "id": number; "items"?: Array<components['schemas']["BusinessBatchItemResponse"]> | null; "last_heartbeat_at"?: string | null; "pending_count": number; "running_count": number; "started_at"?: string | null; "status": string; "tool_id": string; "tool_name": string; "total_count": number; "waiting_count": number; [key: string]: unknown }
    "BusinessBootstrapResponse": { "entitlements": {  }; "product_type": string; "seat_limit": number; "tools": Array<{  }>; [key: string]: unknown }
    "CreateSession": { "capability_key"?: string | null; "platform_key"?: string | null }
    "DebugChatRequest": { "capability_key"?: string | null; "message": string; "platform_key"?: string | null }
    "DemoBatchCreate": { "platform_key": string; "row_count": number; "scenario_id": string; "tool_id": string; "tool_name": string }
    "DemoBatchItemResponse": { "event_seq": number; "finished_at"?: string | null; "item_ref": string; "simulated_outcome"?: "completed_example" | "attention_example" | "failure_example" | null; "started_at"?: string | null; "status": "queued" | "playing" | "played" | "skipped" | "error" }
    "DemoBatchItemUpdate": { "event_seq": number; "simulated_outcome"?: "completed_example" | "attention_example" | "failure_example" | null; "status": "queued" | "playing" | "played" | "skipped" | "error" }
    "DemoBatchResponse": { "created_at": string; "error_count": number; "event_seq": number; "execution_scope"?: "batch"; "finished_at"?: string | null; "id": string; "items"?: Array<components['schemas']["DemoBatchItemResponse"]> | null; "platform_key": string; "played_count": number; "playing_count": number; "queued_count": number; "record_kind"?: "demo"; "row_count": number; "scenario_id": string; "skipped_count": number; "started_at"?: string | null; "status": "created" | "running" | "completed" | "cancelled" | "error"; "tool_id": string; "tool_name_snapshot": string; "updated_at": string }
    "DemoBatchUpdate": { "error_count"?: number | null; "event_seq": number; "played_count"?: number | null; "playing_count"?: number | null; "queued_count"?: number | null; "skipped_count"?: number | null; "status": "created" | "running" | "completed" | "cancelled" | "error" }
    "DemoEvent": { "event_seq": number }
    "DemoRunCreate": { "platform_key": string; "scenario_id": string; "tool_id": string; "tool_name": string; "total_step_count"?: number }
    "DemoRunFinish": { "completed_step_count": number; "event_seq": number; "simulated_outcome"?: "completed_example" | "attention_example" | "failure_example" }
    "DemoRunResponse": { "completed_step_count": number; "created_at": string; "current_step_id"?: string | null; "error_code"?: string | null; "event_seq": number; "execution_scope"?: "single"; "finished_at"?: string | null; "id": string; "platform_key": string; "record_kind"?: "demo"; "scenario_id": string; "simulated_outcome"?: "completed_example" | "attention_example" | "failure_example" | null; "started_at"?: string | null; "status": "created" | "running" | "paused" | "completed" | "cancelled" | "error"; "tool_id": string; "tool_name_snapshot": string; "total_step_count": number; "updated_at": string }
    "DemoRunUpdate": { "completed_step_count"?: number | null; "current_step_id"?: string | null; "error_code"?: string | null; "event_seq": number; "status": "created" | "running" | "paused" | "completed" | "cancelled" | "error" }
    "DeviceResponse": { "created_at"?: string | null; "device_id": string; "device_name"?: string | null; "id": number }
    "ExpenseAttachmentResponse": { "created_at"?: string | null; "expense_id": number; "id": number; "mime_type": string; "original_name": string; "sha256": string; "size_bytes": number }
    "ExpenseCategoryCreate": { "name": string; "sort_order"?: number }
    "ExpenseCategoryResponse": { "code": string; "created_at"?: string | null; "id": number; "is_system": boolean; "name": string; "sort_order": number; "status": "active" | "archived"; "updated_at"?: string | null }
    "ExpenseCategoryTotal": { "category_id": number; "category_name": string; "percentage": string; "total": string }
    "ExpenseCategoryUpdate": { "name"?: string | null; "sort_order"?: number | null; "status"?: "active" | "archived" | null }
    "ExpenseRecordCreate": { "amount": number | string; "category_id": number; "expense_date": string; "note"?: string | null; "payee"?: string | null; "title": string }
    "ExpenseRecordResponse": { "amount": string; "attachments"?: Array<components['schemas']["ExpenseAttachmentResponse"]>; "category_id": number; "category_name": string; "created_at"?: string | null; "created_by_name"?: string | null; "created_by_staff_id"?: number | null; "currency"?: "CNY"; "expense_date": string; "id": number; "note"?: string | null; "payee"?: string | null; "renewal_due_on"?: string | null; "renewal_id"?: number | null; "renewal_name"?: string | null; "status": "active" | "voided"; "title": string; "updated_at"?: string | null; "updated_by_staff_id"?: number | null; "void_reason"?: string | null; "voided_at"?: string | null; "voided_by_staff_id"?: number | null }
    "ExpenseRecordUpdate": { "amount"?: number | string | null; "category_id"?: number | null; "expense_date"?: string | null; "note"?: string | null; "payee"?: string | null; "title"?: string | null }
    "ExpenseRenewalConfirmRequest": { "amount"?: number | string | null; "due_on": string; "expense_date"?: string | null; "note"?: string | null }
    "ExpenseRenewalConfirmResponse": { "expense": components['schemas']["ExpenseRecordResponse"]; "renewal": components['schemas']["ExpenseRenewalResponse"] }
    "ExpenseRenewalCreate": { "category_id": number; "cycle": "monthly" | "quarterly" | "semiannual" | "annual"; "default_amount": number | string; "name": string; "next_due_on": string; "note"?: string | null; "reminder_days"?: number; "vendor"?: string | null }
    "ExpenseRenewalOccurrenceResponse": { "due_on": string; "expense_id"?: number | null; "id": number; "note"?: string | null; "processed_at"?: string | null; "processed_by_staff_id"?: number | null; "renewal_id": number; "status": "paid" | "skipped" }
    "ExpenseRenewalResponse": { "category_id": number; "category_name": string; "created_at"?: string | null; "created_by_staff_id"?: number | null; "cycle": "monthly" | "quarterly" | "semiannual" | "annual"; "default_amount": string; "due_state": "upcoming" | "due" | "overdue" | "scheduled" | "paused" | "ended"; "ended_at"?: string | null; "id": number; "name": string; "next_due_on": string; "note"?: string | null; "occurrences"?: Array<components['schemas']["ExpenseRenewalOccurrenceResponse"]>; "paused_at"?: string | null; "reminder_days": number; "status": "active" | "paused" | "ended"; "updated_at"?: string | null; "updated_by_staff_id"?: number | null; "vendor"?: string | null }
    "ExpenseRenewalResumeRequest": { "next_due_on": string }
    "ExpenseRenewalSkipRequest": { "due_on": string; "note"?: string | null }
    "ExpenseRenewalUpdate": { "category_id"?: number | null; "cycle"?: "monthly" | "quarterly" | "semiannual" | "annual" | null; "default_amount"?: number | string | null; "name"?: string | null; "next_due_on"?: string | null; "note"?: string | null; "reminder_days"?: number | null; "vendor"?: string | null }
    "ExpenseSummaryResponse": { "categories": Array<components['schemas']["ExpenseCategoryTotal"]>; "change_percent": string; "count": number; "month": string; "overdue_renewals": number; "previous_total": string; "total": string; "trend": Array<components['schemas']["ExpenseTrendPoint"]>; "upcoming_renewals": number }
    "ExpenseTrendPoint": { "month": string; "total": string }
    "ExpenseVoidRequest": { "reason": string }
    "FeedbackCreate": { "content"?: string | null; "screenshot"?: string | null; "title"?: string | null; "user_id"?: number | null }
    "FeedbackUpdate": { "admin_reply"?: string | null; "status"?: string | null }
    "HTTPValidationError": { "detail"?: Array<components['schemas']["ValidationError"]> }
    "KnowledgeCreate": { "capability_key"?: string | null; "category": string; "content": string; "keywords"?: Array<string> | null; "platform_key"?: string | null; "priority"?: string | null; "title": string }
    "KnowledgeUpdate": { "capability_key"?: string | null; "category"?: string | null; "content"?: string | null; "keywords"?: Array<string> | null; "platform_key"?: string | null; "priority"?: string | null; "status"?: string | null; "title"?: string | null }
    "LogCreate": { "detail"?: string | null; "device_id"?: string | null; "error_code"?: string | null; "module"?: string | null; "status"?: string | null; "tool_name"?: string | null; "user_id"?: number | null }
    "LogResponse": { "created_at"?: string | null; "detail"?: string | null; "device_id"?: string | null; "error_code"?: string | null; "id": number; "module"?: string | null; "status"?: string | null; "tool_name"?: string | null; "user_id"?: number | null; "verification_state"?: string }
    "OrderCreate": { "amount"?: number | string | null; "channel"?: string | null; "plan_id": number; "platform_key"?: string | null; "responsible"?: string | null }
    "OrderTransitionRequest": { "reason": string }
    "OrderUpdate": { "amount"?: number | string | null; "channel"?: string | null; "plan_id"?: number | null; "platform_key"?: string | null; "responsible"?: string | null }
    "PaginatedDemoBatches": { "data": Array<components['schemas']["DemoBatchResponse"]>; "page": number; "page_size": number; "total": number }
    "PaginatedDemoRuns": { "data": Array<components['schemas']["DemoRunResponse"]>; "page": number; "page_size": number; "total": number }
    "PaginatedResponse_ExpenseRecordResponse_": { "data"?: Array<components['schemas']["ExpenseRecordResponse"]> | null; "message"?: string; "page": number; "page_size": number; "success"?: boolean; "total": number; "total_pages": number }
    "PaginatedResponse_ExpenseRenewalResponse_": { "data"?: Array<components['schemas']["ExpenseRenewalResponse"]> | null; "message"?: string; "page": number; "page_size": number; "success"?: boolean; "total": number; "total_pages": number }
    "PlanCreate": { "code_prefix"?: string | null; "duration_days": number; "entitlements"?: {  } | null; "features"?: string | null; "name": string; "price": number | string; "product_type"?: "consumer" | "business"; "sort_order"?: number }
    "PlanUpdate": { "code_prefix"?: string | null; "duration_days"?: number | null; "entitlements"?: {  } | null; "features"?: string | null; "name"?: string | null; "price"?: number | string | null; "product_type"?: "consumer" | "business" | null; "sort_order"?: number | null }
    "ProfitPolicyUpdate": { "ratios": components['schemas']["ProfitRatios"] }
    "ProfitRatios": { "coordination": number | string; "market": number | string; "product": number | string; "record": number | string; "service": number | string; "tech": number | string }
    "RateSession": { "satisfaction": number }
    "ResolveSession": { "satisfaction"?: number | null }
    "RetrievalTestRequest": { "capability_key"?: string | null; "min_score"?: number; "platform_key"?: string | null; "query": string; "top_k"?: number }
    "RunnerExecutionReport": { "adapter_version"?: string | null; "completed_steps"?: number; "error_code"?: string | null; "page_changed"?: boolean; "page_fingerprint"?: string | null; "run_id": string; "status": string; "token": string }
    "SendMessage": { "capability_key"?: string | null; "message": string; "platform_key"?: string | null }
    "SettingResponse": { "created_at"?: string | null; "description"?: string | null; "id": number; "key": string; "value"?: string | null }
    "SettingUpdate": { "description"?: string | null; "key": string; "value": string }
    "StaffAccountCreate": { "display_name": string; "password": string; "role": "super_admin" | "operator" | "support"; "username": string }
    "StaffAccountUpdate": { "display_name"?: string | null; "role"?: "super_admin" | "operator" | "support" | null; "status"?: "active" | "disabled" | null }
    "StaffLogin": { "password": string; "username": string }
    "StaffPasswordChange": { "current_password": string; "new_password": string }
    "StaffPasswordReset": { "new_password": string }
    "UpdateConfig": { "max_unmatched"?: number | null; "suggested_questions"?: Array<string> | null; "transfer_keywords"?: Array<string> | null; "transfer_rules"?: {  } | null; "welcome_message"?: string | null }
    "UserUpdate": { "extra_devices"?: number | null; "name"?: string | null; "phone"?: string | null; "total_seats"?: number | null }
    "ValidationError": { "loc": Array<string | number>; "msg": string; "type": string }
    "VerifyRequest": { "code": string; "device_id": string; "device_name": string }
  }
}

export interface operations {
  "get_action_center_api_admin_action_center_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_business_batch_api_admin_business_batches__batch_id__get": {
    parameters: { "path": { "batch_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_config_api_ai_chat_admin_config_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "update_config_api_ai_chat_admin_config_put": {
    parameters: never
    requestBody: components['schemas']["UpdateConfig"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "debug_chat_api_ai_chat_admin_debug_post": {
    parameters: never
    requestBody: components['schemas']["DebugChatRequest"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_admin_sessions_api_ai_chat_admin_sessions_get": {
    parameters: { "query": { "status"?: string | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_admin_session_detail_api_ai_chat_admin_sessions__session_id__get": {
    parameters: { "path": { "session_id": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_admin_stats_api_ai_chat_admin_stats_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_history_api_ai_chat_history_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_session_api_ai_chat_session_post": {
    parameters: never
    requestBody: components['schemas']["CreateSession"] | null
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_session_api_ai_chat_session__session_id__get": {
    parameters: { "path": { "session_id": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "send_message_api_ai_chat_session__session_id__message_post": {
    parameters: { "path": { "session_id": string } }
    requestBody: components['schemas']["SendMessage"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "send_message_stream_api_ai_chat_session__session_id__message_stream_post": {
    parameters: { "path": { "session_id": string } }
    requestBody: components['schemas']["SendMessage"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "rate_session_api_ai_chat_session__session_id__rate_post": {
    parameters: { "path": { "session_id": string } }
    requestBody: components['schemas']["RateSession"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "resolve_session_api_ai_chat_session__session_id__resolve_post": {
    parameters: { "path": { "session_id": string } }
    requestBody: components['schemas']["ResolveSession"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "transfer_to_human_api_ai_chat_session__session_id__transfer_post": {
    parameters: { "path": { "session_id": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "list_announcements_api_announcements_get": {
    parameters: { "query": { "status"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_announcement_api_announcements_post": {
    parameters: never
    requestBody: components['schemas']["AnnouncementCreate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_active_announcements_api_announcements_active_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_announcement_feed_api_announcements_feed_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_release_notes_api_announcements_release_notes__version__get": {
    parameters: { "path": { "version": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_announcement_api_announcements__announcement_id__put": {
    parameters: { "path": { "announcement_id": number } }
    requestBody: components['schemas']["AnnouncementUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "delete_announcement_api_announcements__announcement_id__delete": {
    parameters: { "path": { "announcement_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "dismiss_announcement_api_announcements__announcement_id__dismiss_post": {
    parameters: { "path": { "announcement_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "mark_announcement_read_api_announcements__announcement_id__read_post": {
    parameters: { "path": { "announcement_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_auth_codes_api_auth_codes_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "platform_key"?: string; "include_deleted"?: boolean } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "batch_generate_codes_api_auth_codes_batch_generate_post": {
    parameters: never
    requestBody: components['schemas']["AuthCodeGenerate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_auth_code_detail_api_auth_codes__code_id__get": {
    parameters: { "path": { "code_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["AuthCodeResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_auth_code_api_auth_codes__code_id__put": {
    parameters: { "path": { "code_id": number } }
    requestBody: components['schemas']["AuthCodeUpdate"]
    responses: { "200": components['schemas']["AuthCodeResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "delete_auth_code_api_auth_codes__code_id__delete": {
    parameters: { "path": { "code_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "admin_login_api_auth_admin_login_post": {
    parameters: never
    requestBody: components['schemas']["AdminLoginRequest"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "check_auth_status_api_auth_check_post": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_current_user_info_api_auth_me_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "refresh_token_api_auth_refresh_post": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "verify_auth_code_api_auth_verify_post": {
    parameters: never
    requestBody: components['schemas']["VerifyRequest"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "list_batches_api_business_batches_get": {
    parameters: { "query": { "limit"?: number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_list_BusinessBatchResponse__"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_batch_api_business_batches_post": {
    parameters: never
    requestBody: components['schemas']["BatchCreate"]
    responses: { "200": components['schemas']["APIResponse_BusinessBatchResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_batch_api_business_batches__batch_id__get": {
    parameters: { "path": { "batch_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_BusinessBatchResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_batch_api_business_batches__batch_id__patch": {
    parameters: { "path": { "batch_id": number } }
    requestBody: components['schemas']["BatchUpdate"]
    responses: { "200": components['schemas']["APIResponse_BusinessBatchResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "finish_batch_api_business_batches__batch_id__finish_post": {
    parameters: { "path": { "batch_id": number } }
    requestBody: components['schemas']["BatchFinish"]
    responses: { "200": components['schemas']["APIResponse_BusinessBatchResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "upsert_batch_item_api_business_batches__batch_id__items__client_item_id__put": {
    parameters: { "path": { "batch_id": number; "client_item_id": string } }
    requestBody: components['schemas']["BatchItemUpdate"]
    responses: { "200": components['schemas']["APIResponse_BusinessBatchItemResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "bootstrap_api_business_bootstrap_get": {
    parameters: never
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_BusinessBootstrapResponse_"] }
  }
  "get_tools_api_business_tools_get": {
    parameters: never
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_list_dict_str__Any___"] }
  }
  "get_dashboard_api_dashboard_get": {
    parameters: { "query": { "platform_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_dashboard_charts_api_dashboard_charts_get": {
    parameters: { "query": { "platform_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "refresh_dashboard_cache_api_dashboard_refresh_cache_post": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "list_demo_batches_api_demo_batches_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": components['schemas']["PaginatedDemoBatches"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_demo_batch_api_demo_batches_post": {
    parameters: { "header": { "Idempotency-Key"?: string | null } }
    requestBody: components['schemas']["DemoBatchCreate"]
    responses: { "201": components['schemas']["DemoBatchResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_demo_batch_api_demo_batches__batch_id__get": {
    parameters: { "path": { "batch_id": string } }
    requestBody: never
    responses: { "200": components['schemas']["DemoBatchResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_demo_batch_api_demo_batches__batch_id__patch": {
    parameters: { "path": { "batch_id": string } }
    requestBody: components['schemas']["DemoBatchUpdate"]
    responses: { "200": components['schemas']["DemoBatchResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "finish_demo_batch_api_demo_batches__batch_id__finish_post": {
    parameters: { "path": { "batch_id": string } }
    requestBody: components['schemas']["DemoEvent"]
    responses: { "200": components['schemas']["DemoBatchResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_demo_batch_item_api_demo_batches__batch_id__items__item_ref__put": {
    parameters: { "path": { "batch_id": string; "item_ref": string } }
    requestBody: components['schemas']["DemoBatchItemUpdate"]
    responses: { "200": components['schemas']["DemoBatchItemResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "list_demo_runs_api_demo_runs_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "platform_key"?: string | null; "tool_id"?: string | null } }
    requestBody: never
    responses: { "200": components['schemas']["PaginatedDemoRuns"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_demo_run_api_demo_runs_post": {
    parameters: { "header": { "Idempotency-Key"?: string | null } }
    requestBody: components['schemas']["DemoRunCreate"]
    responses: { "201": components['schemas']["DemoRunResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_demo_run_api_demo_runs__run_id__get": {
    parameters: { "path": { "run_id": string } }
    requestBody: never
    responses: { "200": components['schemas']["DemoRunResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_demo_run_api_demo_runs__run_id__patch": {
    parameters: { "path": { "run_id": string } }
    requestBody: components['schemas']["DemoRunUpdate"]
    responses: { "200": components['schemas']["DemoRunResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "cancel_demo_run_api_demo_runs__run_id__cancel_post": {
    parameters: { "path": { "run_id": string } }
    requestBody: components['schemas']["DemoEvent"]
    responses: { "200": components['schemas']["DemoRunResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "finish_demo_run_api_demo_runs__run_id__finish_post": {
    parameters: { "path": { "run_id": string } }
    requestBody: components['schemas']["DemoRunFinish"]
    responses: { "200": components['schemas']["DemoRunResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_devices_api_devices_get": {
    parameters: { "query": { "auth_code_id"?: number | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_my_devices_api_devices_my_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "unbind_device_api_devices_unbind_post": {
    parameters: { "query": { "device_id": number; "reason": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "user_unbind_device_api_devices_user_unbind_post": {
    parameters: { "query": { "device_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "list_executions_api_executions_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "platform_key"?: string | null; "tool_id"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "report_execution_api_executions_report_post": {
    parameters: never
    requestBody: components['schemas']["RunnerExecutionReport"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_execution_api_executions__execution_id__get": {
    parameters: { "path": { "execution_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_expenses_api_expenses_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "month"?: string | null; "category_id"?: number | null; "status"?: string | null; "q"?: string | null } }
    requestBody: never
    responses: { "200": components['schemas']["PaginatedResponse_ExpenseRecordResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_expense_api_expenses_post": {
    parameters: never
    requestBody: components['schemas']["ExpenseRecordCreate"]
    responses: { "201": components['schemas']["APIResponse_ExpenseRecordResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_expense_categories_api_expenses_categories_get": {
    parameters: { "query": { "include_archived"?: boolean } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_list_ExpenseCategoryResponse__"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_expense_category_api_expenses_categories_post": {
    parameters: never
    requestBody: components['schemas']["ExpenseCategoryCreate"]
    responses: { "201": components['schemas']["APIResponse_ExpenseCategoryResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_expense_category_api_expenses_categories__category_id__patch": {
    parameters: { "path": { "category_id": number } }
    requestBody: components['schemas']["ExpenseCategoryUpdate"]
    responses: { "200": components['schemas']["APIResponse_ExpenseCategoryResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "export_expenses_api_expenses_export_get": {
    parameters: { "query": { "month"?: string | null; "category_id"?: number | null; "status"?: string | null; "q"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_expense_renewals_api_expenses_renewals_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "status"?: string | null; "due_state"?: string | null; "q"?: string | null } }
    requestBody: never
    responses: { "200": components['schemas']["PaginatedResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_expense_renewal_api_expenses_renewals_post": {
    parameters: never
    requestBody: components['schemas']["ExpenseRenewalCreate"]
    responses: { "201": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_expense_renewal_api_expenses_renewals__renewal_id__get": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_expense_renewal_api_expenses_renewals__renewal_id__patch": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: components['schemas']["ExpenseRenewalUpdate"]
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "confirm_expense_renewal_api_expenses_renewals__renewal_id__confirm_post": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: components['schemas']["ExpenseRenewalConfirmRequest"]
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalConfirmResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "end_expense_renewal_api_expenses_renewals__renewal_id__end_post": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "pause_expense_renewal_api_expenses_renewals__renewal_id__pause_post": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "resume_expense_renewal_api_expenses_renewals__renewal_id__resume_post": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: components['schemas']["ExpenseRenewalResumeRequest"]
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "skip_expense_renewal_api_expenses_renewals__renewal_id__skip_post": {
    parameters: { "path": { "renewal_id": number } }
    requestBody: components['schemas']["ExpenseRenewalSkipRequest"]
    responses: { "200": components['schemas']["APIResponse_ExpenseRenewalResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_expense_summary_api_expenses_summary_get": {
    parameters: { "query": { "month"?: string | null } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_ExpenseSummaryResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_expense_api_expenses__expense_id__get": {
    parameters: { "path": { "expense_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_ExpenseRecordResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_expense_api_expenses__expense_id__patch": {
    parameters: { "path": { "expense_id": number } }
    requestBody: components['schemas']["ExpenseRecordUpdate"]
    responses: { "200": components['schemas']["APIResponse_ExpenseRecordResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "add_expense_attachment_api_expenses__expense_id__attachments_post": {
    parameters: { "path": { "expense_id": number } }
    requestBody: components['schemas']["Body_add_expense_attachment_api_expenses__expense_id__attachments_post"]
    responses: { "201": components['schemas']["APIResponse_ExpenseAttachmentResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "download_expense_attachment_api_expenses__expense_id__attachments__attachment_id__get": {
    parameters: { "path": { "expense_id": number; "attachment_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "delete_expense_attachment_api_expenses__expense_id__attachments__attachment_id__delete": {
    parameters: { "path": { "expense_id": number; "attachment_id": number } }
    requestBody: never
    responses: { "200": components['schemas']["APIResponse_NoneType_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "void_expense_api_expenses__expense_id__void_post": {
    parameters: { "path": { "expense_id": number } }
    requestBody: components['schemas']["ExpenseVoidRequest"]
    responses: { "200": components['schemas']["APIResponse_ExpenseRecordResponse_"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_feedback_list_api_feedback_get": {
    parameters: { "query": { "status"?: string | null; "platform_key"?: string | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_feedback_api_feedback_post": {
    parameters: never
    requestBody: components['schemas']["FeedbackCreate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_my_feedback_api_feedback_my_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_feedback_stats_api_feedback_stats_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_feedback_api_feedback__feedback_id__get": {
    parameters: { "path": { "feedback_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_feedback_api_feedback__feedback_id__put": {
    parameters: { "path": { "feedback_id": number } }
    requestBody: components['schemas']["FeedbackUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "delete_feedback_api_feedback__feedback_id__delete": {
    parameters: { "path": { "feedback_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "list_rate_releases_api_freight_rate_packs_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_current_rate_pack_api_freight_rate_packs_current_get": {
    parameters: { "query": { "pack_id"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_draft_api_freight_rate_packs_drafts_post": {
    parameters: never
    requestBody: {  }
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "rollback_rate_pack_api_freight_rate_packs__pack_id__rollback_post": {
    parameters: { "path": { "pack_id": string } }
    requestBody: {  }
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_rate_artifact_api_freight_rate_packs__pack_id___version__artifact_get": {
    parameters: { "path": { "pack_id": string; "version": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "publish_rate_pack_api_freight_rate_packs__pack_id___version__publish_post": {
    parameters: { "path": { "pack_id": string; "version": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "health_check_api_health_get": {
    parameters: never
    requestBody: never
    responses: { "200": {  } }
  }
  "health_live_api_health_live_get": {
    parameters: never
    requestBody: never
    responses: { "200": {  } }
  }
  "health_ready_api_health_ready_get": {
    parameters: never
    requestBody: never
    responses: { "200": {  } }
  }
  "get_faq_list_api_help_faq_list_get": {
    parameters: { "query": { "platform_key"?: string | null; "capability_key"?: string | null; "category"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "query_help_api_help_query_post": {
    parameters: never
    requestBody: {  }
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_knowledge_list_api_knowledge_get": {
    parameters: { "query": { "category"?: string | null; "status"?: string | null; "keyword"?: string | null; "platform_key"?: string | null; "capability_key"?: string | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_knowledge_api_knowledge_post": {
    parameters: never
    requestBody: components['schemas']["KnowledgeCreate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "batch_import_api_knowledge_batch_import_post": {
    parameters: never
    requestBody: Array<components['schemas']["BatchImportItem"]>
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_categories_api_knowledge_categories_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "retrieval_test_api_knowledge_retrieval_test_post": {
    parameters: never
    requestBody: components['schemas']["RetrievalTestRequest"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_stats_api_knowledge_stats_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "sync_to_vector_api_knowledge_sync_vector_post": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_knowledge_api_knowledge__knowledge_id__get": {
    parameters: { "path": { "knowledge_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_knowledge_api_knowledge__knowledge_id__put": {
    parameters: { "path": { "knowledge_id": number } }
    requestBody: components['schemas']["KnowledgeUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "delete_knowledge_api_knowledge__knowledge_id__delete": {
    parameters: { "path": { "knowledge_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_logs_api_logs_get": {
    parameters: { "query": { "user_id"?: number | null; "start_date"?: string | null; "end_date"?: string | null; "tool_name"?: string | null; "status"?: string | null; "platform_key"?: string | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_log_api_logs_post": {
    parameters: never
    requestBody: components['schemas']["LogCreate"]
    responses: { "200": components['schemas']["LogResponse"]; "422": components['schemas']["HTTPValidationError"] }
  }
  "export_logs_api_logs_export_get": {
    parameters: { "query": { "user_id"?: number | null; "start_date"?: string | null; "end_date"?: string | null; "tool_name"?: string | null; "status"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_log_tools_api_logs_tools_get": {
    parameters: { "query": { "user_id"?: number | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_orders_api_orders_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "status"?: string | null; "plan_id"?: number | null; "platform_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_order_api_orders_post": {
    parameters: never
    requestBody: components['schemas']["OrderCreate"]
    responses: { "201": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "export_orders_api_orders_export_get": {
    parameters: { "query": { "status"?: string | null; "start_date"?: string | null; "end_date"?: string | null; "platform_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_order_api_orders__order_id__get": {
    parameters: { "path": { "order_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_order_api_orders__order_id__put": {
    parameters: { "path": { "order_id": number } }
    requestBody: components['schemas']["OrderUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_order_api_orders__order_id__patch": {
    parameters: { "path": { "order_id": number } }
    requestBody: components['schemas']["OrderUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "cancel_order_api_orders__order_id__cancel_post": {
    parameters: { "path": { "order_id": number } }
    requestBody: components['schemas']["OrderTransitionRequest"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "mark_order_paid_api_orders__order_id__mark_paid_post": {
    parameters: { "path": { "order_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "refund_order_api_orders__order_id__refund_post": {
    parameters: { "path": { "order_id": number } }
    requestBody: components['schemas']["OrderTransitionRequest"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_plans_api_plans_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "create_plan_api_plans_post": {
    parameters: never
    requestBody: components['schemas']["PlanCreate"]
    responses: { "201": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_plans_admin_api_plans_admin_get": {
    parameters: { "query": { "status"?: string | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_plan_api_plans__plan_id__get": {
    parameters: { "path": { "plan_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_plan_api_plans__plan_id__put": {
    parameters: { "path": { "plan_id": number } }
    requestBody: components['schemas']["PlanUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_plan_api_plans__plan_id__patch": {
    parameters: { "path": { "plan_id": number } }
    requestBody: components['schemas']["PlanUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "archive_plan_compatibility_api_plans__plan_id__delete": {
    parameters: { "path": { "plan_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "archive_plan_api_plans__plan_id__archive_post": {
    parameters: { "path": { "plan_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "disable_plan_api_plans__plan_id__disable_post": {
    parameters: { "path": { "plan_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "enable_plan_api_plans__plan_id__enable_post": {
    parameters: { "path": { "plan_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_plan_stats_api_plans__plan_id__stats_get": {
    parameters: { "path": { "plan_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_profit_records_api_profit_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number; "platform_key"?: string | null; "status"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_profit_policy_api_profit_policy_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "update_profit_policy_api_profit_policy_put": {
    parameters: never
    requestBody: components['schemas']["ProfitPolicyUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_profit_summary_api_profit_summary_get": {
    parameters: { "query": { "platform_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_all_settings_api_settings_get": {
    parameters: never
    requestBody: never
    responses: { "200": Array<components['schemas']["SettingResponse"]> }
  }
  "update_setting_api_settings_put": {
    parameters: never
    requestBody: components['schemas']["SettingUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_public_settings_api_settings_public_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "list_accounts_api_staff_accounts_get": {
    parameters: { "query": { "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_account_api_staff_accounts_post": {
    parameters: never
    requestBody: components['schemas']["StaffAccountCreate"]
    responses: { "201": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_account_api_staff_accounts__staff_id__patch": {
    parameters: { "path": { "staff_id": number } }
    requestBody: components['schemas']["StaffAccountUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "reset_password_api_staff_accounts__staff_id__reset_password_post": {
    parameters: { "path": { "staff_id": number } }
    requestBody: components['schemas']["StaffPasswordReset"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "change_password_api_staff_auth_change_password_post": {
    parameters: never
    requestBody: components['schemas']["StaffPasswordChange"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "login_api_staff_auth_login_post": {
    parameters: never
    requestBody: components['schemas']["StaffLogin"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "logout_api_staff_auth_logout_post": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "me_api_staff_auth_me_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "system_info_api_system_info_get": {
    parameters: never
    requestBody: never
    responses: { "200": {  } }
  }
  "list_tool_releases_api_tool_releases_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "add_tool_release_api_tool_releases_post": {
    parameters: never
    requestBody: {  }
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "rollback_tool_release_api_tool_releases__tool_id__rollback_post": {
    parameters: { "path": { "tool_id": string } }
    requestBody: {  }
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_tool_release_artifact_api_tool_releases__tool_id___version__artifact_get": {
    parameters: { "path": { "tool_id": string; "version": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "publish_tool_release_api_tool_releases__tool_id___version__publish_post": {
    parameters: { "path": { "tool_id": string; "version": string } }
    requestBody: {  }
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_tools_api_tools_get": {
    parameters: { "query": { "category"?: string | null; "search"?: string | null; "platform_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_tools_api_tools_put": {
    parameters: never
    requestBody: Array<{  }>
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_tool_categories_api_tools_categories_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "update_tool_categories_api_tools_categories_put": {
    parameters: never
    requestBody: components['schemas']["Body_update_tool_categories_api_tools_categories_put"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "verify_launch_token_api_tools_launch_grant_verify_post": {
    parameters: { "query": { "token": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "verify_launch_token_api_tools_launch_token_verify_post": {
    parameters: { "query": { "token": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_platforms_api_tools_platforms_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "update_platforms_api_tools_platforms_put": {
    parameters: never
    requestBody: components['schemas']["Body_update_platforms_api_tools_platforms_put"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_launch_token_api_tools__tool_id__launch_grant_post": {
    parameters: { "path": { "tool_id": string }; "query": { "platform_key": string; "execution_mode"?: string; "client_batch_id"?: string | null; "client_item_id"?: string | null; "idempotency_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "create_launch_token_api_tools__tool_id__launch_token_post": {
    parameters: { "path": { "tool_id": string }; "query": { "platform_key": string; "execution_mode"?: string; "client_batch_id"?: string | null; "client_item_id"?: string | null; "idempotency_key"?: string | null } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "list_updates_api_updates_list_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "list_releases_api_updates_releases_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "stage_release_api_updates_releases_stage_post": {
    parameters: never
    requestBody: components['schemas']["Body_stage_release_api_updates_releases_stage_post"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "publish_release_api_updates_releases__version__publish_post": {
    parameters: { "path": { "version": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "delete_staged_release_api_updates_releases__version__staged_delete": {
    parameters: { "path": { "version": string } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_users_api_users_get": {
    parameters: { "query": { "keyword"?: string | null; "page"?: number; "page_size"?: number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_user_stats_api_users_stats_get": {
    parameters: never
    requestBody: never
    responses: { "200": unknown }
  }
  "get_user_api_users__user_id__get": {
    parameters: { "path": { "user_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "update_user_api_users__user_id__put": {
    parameters: { "path": { "user_id": number } }
    requestBody: components['schemas']["UserUpdate"]
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
  "get_user_devices_api_users__user_id__devices_get": {
    parameters: { "path": { "user_id": number } }
    requestBody: never
    responses: { "200": unknown; "422": components['schemas']["HTTPValidationError"] }
  }
}

export interface paths {
  "/api/admin/action-center": {
    get: operations["get_action_center_api_admin_action_center_get"]
  }
  "/api/admin/business-batches/{batch_id}": {
    get: operations["get_business_batch_api_admin_business_batches__batch_id__get"]
  }
  "/api/ai-chat/admin/config": {
    get: operations["get_config_api_ai_chat_admin_config_get"]
    put: operations["update_config_api_ai_chat_admin_config_put"]
  }
  "/api/ai-chat/admin/debug": {
    post: operations["debug_chat_api_ai_chat_admin_debug_post"]
  }
  "/api/ai-chat/admin/sessions": {
    get: operations["get_admin_sessions_api_ai_chat_admin_sessions_get"]
  }
  "/api/ai-chat/admin/sessions/{session_id}": {
    get: operations["get_admin_session_detail_api_ai_chat_admin_sessions__session_id__get"]
  }
  "/api/ai-chat/admin/stats": {
    get: operations["get_admin_stats_api_ai_chat_admin_stats_get"]
  }
  "/api/ai-chat/history": {
    get: operations["get_history_api_ai_chat_history_get"]
  }
  "/api/ai-chat/session": {
    post: operations["create_session_api_ai_chat_session_post"]
  }
  "/api/ai-chat/session/{session_id}": {
    get: operations["get_session_api_ai_chat_session__session_id__get"]
  }
  "/api/ai-chat/session/{session_id}/message": {
    post: operations["send_message_api_ai_chat_session__session_id__message_post"]
  }
  "/api/ai-chat/session/{session_id}/message/stream": {
    post: operations["send_message_stream_api_ai_chat_session__session_id__message_stream_post"]
  }
  "/api/ai-chat/session/{session_id}/rate": {
    post: operations["rate_session_api_ai_chat_session__session_id__rate_post"]
  }
  "/api/ai-chat/session/{session_id}/resolve": {
    post: operations["resolve_session_api_ai_chat_session__session_id__resolve_post"]
  }
  "/api/ai-chat/session/{session_id}/transfer": {
    post: operations["transfer_to_human_api_ai_chat_session__session_id__transfer_post"]
  }
  "/api/announcements": {
    get: operations["list_announcements_api_announcements_get"]
    post: operations["create_announcement_api_announcements_post"]
  }
  "/api/announcements/active": {
    get: operations["get_active_announcements_api_announcements_active_get"]
  }
  "/api/announcements/feed": {
    get: operations["get_announcement_feed_api_announcements_feed_get"]
  }
  "/api/announcements/release-notes/{version}": {
    get: operations["get_release_notes_api_announcements_release_notes__version__get"]
  }
  "/api/announcements/{announcement_id}": {
    put: operations["update_announcement_api_announcements__announcement_id__put"]
    delete: operations["delete_announcement_api_announcements__announcement_id__delete"]
  }
  "/api/announcements/{announcement_id}/dismiss": {
    post: operations["dismiss_announcement_api_announcements__announcement_id__dismiss_post"]
  }
  "/api/announcements/{announcement_id}/read": {
    post: operations["mark_announcement_read_api_announcements__announcement_id__read_post"]
  }
  "/api/auth-codes": {
    get: operations["get_auth_codes_api_auth_codes_get"]
  }
  "/api/auth-codes/batch-generate": {
    post: operations["batch_generate_codes_api_auth_codes_batch_generate_post"]
  }
  "/api/auth-codes/{code_id}": {
    get: operations["get_auth_code_detail_api_auth_codes__code_id__get"]
    put: operations["update_auth_code_api_auth_codes__code_id__put"]
    delete: operations["delete_auth_code_api_auth_codes__code_id__delete"]
  }
  "/api/auth/admin-login": {
    post: operations["admin_login_api_auth_admin_login_post"]
  }
  "/api/auth/check": {
    post: operations["check_auth_status_api_auth_check_post"]
  }
  "/api/auth/me": {
    get: operations["get_current_user_info_api_auth_me_get"]
  }
  "/api/auth/refresh": {
    post: operations["refresh_token_api_auth_refresh_post"]
  }
  "/api/auth/verify": {
    post: operations["verify_auth_code_api_auth_verify_post"]
  }
  "/api/business/batches": {
    get: operations["list_batches_api_business_batches_get"]
    post: operations["create_batch_api_business_batches_post"]
  }
  "/api/business/batches/{batch_id}": {
    get: operations["get_batch_api_business_batches__batch_id__get"]
    patch: operations["update_batch_api_business_batches__batch_id__patch"]
  }
  "/api/business/batches/{batch_id}/finish": {
    post: operations["finish_batch_api_business_batches__batch_id__finish_post"]
  }
  "/api/business/batches/{batch_id}/items/{client_item_id}": {
    put: operations["upsert_batch_item_api_business_batches__batch_id__items__client_item_id__put"]
  }
  "/api/business/bootstrap": {
    get: operations["bootstrap_api_business_bootstrap_get"]
  }
  "/api/business/tools": {
    get: operations["get_tools_api_business_tools_get"]
  }
  "/api/dashboard": {
    get: operations["get_dashboard_api_dashboard_get"]
  }
  "/api/dashboard/charts": {
    get: operations["get_dashboard_charts_api_dashboard_charts_get"]
  }
  "/api/dashboard/refresh-cache": {
    post: operations["refresh_dashboard_cache_api_dashboard_refresh_cache_post"]
  }
  "/api/demo/batches": {
    get: operations["list_demo_batches_api_demo_batches_get"]
    post: operations["create_demo_batch_api_demo_batches_post"]
  }
  "/api/demo/batches/{batch_id}": {
    get: operations["get_demo_batch_api_demo_batches__batch_id__get"]
    patch: operations["update_demo_batch_api_demo_batches__batch_id__patch"]
  }
  "/api/demo/batches/{batch_id}/finish": {
    post: operations["finish_demo_batch_api_demo_batches__batch_id__finish_post"]
  }
  "/api/demo/batches/{batch_id}/items/{item_ref}": {
    put: operations["update_demo_batch_item_api_demo_batches__batch_id__items__item_ref__put"]
  }
  "/api/demo/runs": {
    get: operations["list_demo_runs_api_demo_runs_get"]
    post: operations["create_demo_run_api_demo_runs_post"]
  }
  "/api/demo/runs/{run_id}": {
    get: operations["get_demo_run_api_demo_runs__run_id__get"]
    patch: operations["update_demo_run_api_demo_runs__run_id__patch"]
  }
  "/api/demo/runs/{run_id}/cancel": {
    post: operations["cancel_demo_run_api_demo_runs__run_id__cancel_post"]
  }
  "/api/demo/runs/{run_id}/finish": {
    post: operations["finish_demo_run_api_demo_runs__run_id__finish_post"]
  }
  "/api/devices": {
    get: operations["get_devices_api_devices_get"]
  }
  "/api/devices/my": {
    get: operations["get_my_devices_api_devices_my_get"]
  }
  "/api/devices/unbind": {
    post: operations["unbind_device_api_devices_unbind_post"]
  }
  "/api/devices/user-unbind": {
    post: operations["user_unbind_device_api_devices_user_unbind_post"]
  }
  "/api/executions": {
    get: operations["list_executions_api_executions_get"]
  }
  "/api/executions/report": {
    post: operations["report_execution_api_executions_report_post"]
  }
  "/api/executions/{execution_id}": {
    get: operations["get_execution_api_executions__execution_id__get"]
  }
  "/api/expenses": {
    get: operations["get_expenses_api_expenses_get"]
    post: operations["create_expense_api_expenses_post"]
  }
  "/api/expenses/categories": {
    get: operations["get_expense_categories_api_expenses_categories_get"]
    post: operations["create_expense_category_api_expenses_categories_post"]
  }
  "/api/expenses/categories/{category_id}": {
    patch: operations["update_expense_category_api_expenses_categories__category_id__patch"]
  }
  "/api/expenses/export": {
    get: operations["export_expenses_api_expenses_export_get"]
  }
  "/api/expenses/renewals": {
    get: operations["get_expense_renewals_api_expenses_renewals_get"]
    post: operations["create_expense_renewal_api_expenses_renewals_post"]
  }
  "/api/expenses/renewals/{renewal_id}": {
    get: operations["get_expense_renewal_api_expenses_renewals__renewal_id__get"]
    patch: operations["update_expense_renewal_api_expenses_renewals__renewal_id__patch"]
  }
  "/api/expenses/renewals/{renewal_id}/confirm": {
    post: operations["confirm_expense_renewal_api_expenses_renewals__renewal_id__confirm_post"]
  }
  "/api/expenses/renewals/{renewal_id}/end": {
    post: operations["end_expense_renewal_api_expenses_renewals__renewal_id__end_post"]
  }
  "/api/expenses/renewals/{renewal_id}/pause": {
    post: operations["pause_expense_renewal_api_expenses_renewals__renewal_id__pause_post"]
  }
  "/api/expenses/renewals/{renewal_id}/resume": {
    post: operations["resume_expense_renewal_api_expenses_renewals__renewal_id__resume_post"]
  }
  "/api/expenses/renewals/{renewal_id}/skip": {
    post: operations["skip_expense_renewal_api_expenses_renewals__renewal_id__skip_post"]
  }
  "/api/expenses/summary": {
    get: operations["get_expense_summary_api_expenses_summary_get"]
  }
  "/api/expenses/{expense_id}": {
    get: operations["get_expense_api_expenses__expense_id__get"]
    patch: operations["update_expense_api_expenses__expense_id__patch"]
  }
  "/api/expenses/{expense_id}/attachments": {
    post: operations["add_expense_attachment_api_expenses__expense_id__attachments_post"]
  }
  "/api/expenses/{expense_id}/attachments/{attachment_id}": {
    get: operations["download_expense_attachment_api_expenses__expense_id__attachments__attachment_id__get"]
    delete: operations["delete_expense_attachment_api_expenses__expense_id__attachments__attachment_id__delete"]
  }
  "/api/expenses/{expense_id}/void": {
    post: operations["void_expense_api_expenses__expense_id__void_post"]
  }
  "/api/feedback": {
    get: operations["get_feedback_list_api_feedback_get"]
    post: operations["create_feedback_api_feedback_post"]
  }
  "/api/feedback/my": {
    get: operations["get_my_feedback_api_feedback_my_get"]
  }
  "/api/feedback/stats": {
    get: operations["get_feedback_stats_api_feedback_stats_get"]
  }
  "/api/feedback/{feedback_id}": {
    get: operations["get_feedback_api_feedback__feedback_id__get"]
    put: operations["update_feedback_api_feedback__feedback_id__put"]
    delete: operations["delete_feedback_api_feedback__feedback_id__delete"]
  }
  "/api/freight-rate-packs": {
    get: operations["list_rate_releases_api_freight_rate_packs_get"]
  }
  "/api/freight-rate-packs/current": {
    get: operations["get_current_rate_pack_api_freight_rate_packs_current_get"]
  }
  "/api/freight-rate-packs/drafts": {
    post: operations["create_draft_api_freight_rate_packs_drafts_post"]
  }
  "/api/freight-rate-packs/{pack_id}/rollback": {
    post: operations["rollback_rate_pack_api_freight_rate_packs__pack_id__rollback_post"]
  }
  "/api/freight-rate-packs/{pack_id}/{version}/artifact": {
    get: operations["get_rate_artifact_api_freight_rate_packs__pack_id___version__artifact_get"]
  }
  "/api/freight-rate-packs/{pack_id}/{version}/publish": {
    post: operations["publish_rate_pack_api_freight_rate_packs__pack_id___version__publish_post"]
  }
  "/api/health": {
    get: operations["health_check_api_health_get"]
  }
  "/api/health/live": {
    get: operations["health_live_api_health_live_get"]
  }
  "/api/health/ready": {
    get: operations["health_ready_api_health_ready_get"]
  }
  "/api/help/faq/list": {
    get: operations["get_faq_list_api_help_faq_list_get"]
  }
  "/api/help/query": {
    post: operations["query_help_api_help_query_post"]
  }
  "/api/knowledge": {
    get: operations["get_knowledge_list_api_knowledge_get"]
    post: operations["create_knowledge_api_knowledge_post"]
  }
  "/api/knowledge/batch-import": {
    post: operations["batch_import_api_knowledge_batch_import_post"]
  }
  "/api/knowledge/categories": {
    get: operations["get_categories_api_knowledge_categories_get"]
  }
  "/api/knowledge/retrieval-test": {
    post: operations["retrieval_test_api_knowledge_retrieval_test_post"]
  }
  "/api/knowledge/stats": {
    get: operations["get_stats_api_knowledge_stats_get"]
  }
  "/api/knowledge/sync-vector": {
    post: operations["sync_to_vector_api_knowledge_sync_vector_post"]
  }
  "/api/knowledge/{knowledge_id}": {
    get: operations["get_knowledge_api_knowledge__knowledge_id__get"]
    put: operations["update_knowledge_api_knowledge__knowledge_id__put"]
    delete: operations["delete_knowledge_api_knowledge__knowledge_id__delete"]
  }
  "/api/logs": {
    get: operations["get_logs_api_logs_get"]
    post: operations["create_log_api_logs_post"]
  }
  "/api/logs/export": {
    get: operations["export_logs_api_logs_export_get"]
  }
  "/api/logs/tools": {
    get: operations["get_log_tools_api_logs_tools_get"]
  }
  "/api/orders": {
    get: operations["get_orders_api_orders_get"]
    post: operations["create_order_api_orders_post"]
  }
  "/api/orders/export": {
    get: operations["export_orders_api_orders_export_get"]
  }
  "/api/orders/{order_id}": {
    get: operations["get_order_api_orders__order_id__get"]
    put: operations["update_order_api_orders__order_id__put"]
    patch: operations["update_order_api_orders__order_id__patch"]
  }
  "/api/orders/{order_id}/cancel": {
    post: operations["cancel_order_api_orders__order_id__cancel_post"]
  }
  "/api/orders/{order_id}/mark-paid": {
    post: operations["mark_order_paid_api_orders__order_id__mark_paid_post"]
  }
  "/api/orders/{order_id}/refund": {
    post: operations["refund_order_api_orders__order_id__refund_post"]
  }
  "/api/plans": {
    get: operations["get_plans_api_plans_get"]
    post: operations["create_plan_api_plans_post"]
  }
  "/api/plans/admin": {
    get: operations["get_plans_admin_api_plans_admin_get"]
  }
  "/api/plans/{plan_id}": {
    get: operations["get_plan_api_plans__plan_id__get"]
    put: operations["update_plan_api_plans__plan_id__put"]
    patch: operations["update_plan_api_plans__plan_id__patch"]
    delete: operations["archive_plan_compatibility_api_plans__plan_id__delete"]
  }
  "/api/plans/{plan_id}/archive": {
    post: operations["archive_plan_api_plans__plan_id__archive_post"]
  }
  "/api/plans/{plan_id}/disable": {
    post: operations["disable_plan_api_plans__plan_id__disable_post"]
  }
  "/api/plans/{plan_id}/enable": {
    post: operations["enable_plan_api_plans__plan_id__enable_post"]
  }
  "/api/plans/{plan_id}/stats": {
    get: operations["get_plan_stats_api_plans__plan_id__stats_get"]
  }
  "/api/profit": {
    get: operations["get_profit_records_api_profit_get"]
  }
  "/api/profit/policy": {
    get: operations["get_profit_policy_api_profit_policy_get"]
    put: operations["update_profit_policy_api_profit_policy_put"]
  }
  "/api/profit/summary": {
    get: operations["get_profit_summary_api_profit_summary_get"]
  }
  "/api/settings": {
    get: operations["get_all_settings_api_settings_get"]
    put: operations["update_setting_api_settings_put"]
  }
  "/api/settings/public": {
    get: operations["get_public_settings_api_settings_public_get"]
  }
  "/api/staff/accounts": {
    get: operations["list_accounts_api_staff_accounts_get"]
    post: operations["create_account_api_staff_accounts_post"]
  }
  "/api/staff/accounts/{staff_id}": {
    patch: operations["update_account_api_staff_accounts__staff_id__patch"]
  }
  "/api/staff/accounts/{staff_id}/reset-password": {
    post: operations["reset_password_api_staff_accounts__staff_id__reset_password_post"]
  }
  "/api/staff/auth/change-password": {
    post: operations["change_password_api_staff_auth_change_password_post"]
  }
  "/api/staff/auth/login": {
    post: operations["login_api_staff_auth_login_post"]
  }
  "/api/staff/auth/logout": {
    post: operations["logout_api_staff_auth_logout_post"]
  }
  "/api/staff/auth/me": {
    get: operations["me_api_staff_auth_me_get"]
  }
  "/api/system-info": {
    get: operations["system_info_api_system_info_get"]
  }
  "/api/tool-releases": {
    get: operations["list_tool_releases_api_tool_releases_get"]
    post: operations["add_tool_release_api_tool_releases_post"]
  }
  "/api/tool-releases/{tool_id}/rollback": {
    post: operations["rollback_tool_release_api_tool_releases__tool_id__rollback_post"]
  }
  "/api/tool-releases/{tool_id}/{version}/artifact": {
    get: operations["get_tool_release_artifact_api_tool_releases__tool_id___version__artifact_get"]
  }
  "/api/tool-releases/{tool_id}/{version}/publish": {
    post: operations["publish_tool_release_api_tool_releases__tool_id___version__publish_post"]
  }
  "/api/tools": {
    get: operations["get_tools_api_tools_get"]
    put: operations["update_tools_api_tools_put"]
  }
  "/api/tools/categories": {
    get: operations["get_tool_categories_api_tools_categories_get"]
    put: operations["update_tool_categories_api_tools_categories_put"]
  }
  "/api/tools/launch-grant/verify": {
    post: operations["verify_launch_token_api_tools_launch_grant_verify_post"]
  }
  "/api/tools/launch-token/verify": {
    post: operations["verify_launch_token_api_tools_launch_token_verify_post"]
  }
  "/api/tools/platforms": {
    get: operations["get_platforms_api_tools_platforms_get"]
    put: operations["update_platforms_api_tools_platforms_put"]
  }
  "/api/tools/{tool_id}/launch-grant": {
    post: operations["create_launch_token_api_tools__tool_id__launch_grant_post"]
  }
  "/api/tools/{tool_id}/launch-token": {
    post: operations["create_launch_token_api_tools__tool_id__launch_token_post"]
  }
  "/api/updates/list": {
    get: operations["list_updates_api_updates_list_get"]
  }
  "/api/updates/releases": {
    get: operations["list_releases_api_updates_releases_get"]
  }
  "/api/updates/releases/stage": {
    post: operations["stage_release_api_updates_releases_stage_post"]
  }
  "/api/updates/releases/{version}/publish": {
    post: operations["publish_release_api_updates_releases__version__publish_post"]
  }
  "/api/updates/releases/{version}/staged": {
    delete: operations["delete_staged_release_api_updates_releases__version__staged_delete"]
  }
  "/api/users": {
    get: operations["get_users_api_users_get"]
  }
  "/api/users/stats": {
    get: operations["get_user_stats_api_users_stats_get"]
  }
  "/api/users/{user_id}": {
    get: operations["get_user_api_users__user_id__get"]
    put: operations["update_user_api_users__user_id__put"]
  }
  "/api/users/{user_id}/devices": {
    get: operations["get_user_devices_api_users__user_id__devices_get"]
  }
}
